os: linux
dist: bionic
language: php

env:
    global:
        - MINK_DEBUG_CACHE_DIR=$HOME/.mink-debug-cache
        - COMPOSER_OPTIONS=""

jobs:
    include:
        - name: PHP 7.4 Latest dependencies
          php: 7.4
        - name: PHP 7.4 Oldest dependencies
          php: 7.4
          env: COMPOSER_OPTIONS="--prefer-lowest"
        - name: PHP 7.3 Latest dependencies
          php: 7.3
        - name: PHP 7.3 Oldest dependencies
          php: 7.3
          env: COMPOSER_OPTIONS="--prefer-lowest"
        - name: PHP 7.2 Latest dependencies
          php: 7.2
        - name: PHP 7.2 Oldest dependencies
          php: 7.2
          env: COMPOSER_OPTIONS="--prefer-lowest"

cache:
    directories:
        - ~/.composer/cache/files
        - $MINK_DEBUG_CACHE_DIR

before_install:
    - phpenv config-rm xdebug.ini || true
    - mkdir -p $MINK_DEBUG_CACHE_DIR
    - composer self-update

install:
    - composer update --prefer-dist $COMPOSER_OPTIONS

before_script:
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
    - export DISPLAY=:99

    # Download and configure ChromeDriver
    - |
      if [ ! -f $MINK_DEBUG_CACHE_DIR/chromedriver ] || [ "$($MINK_DEBUG_CACHE_DIR/chromedriver --version | grep -c 80.0.3987.106)" = "0" ]; then
          curl https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip > chromedriver.zip
          unzip chromedriver.zip
          chmod +x chromedriver
          mv chromedriver $MINK_DEBUG_CACHE_DIR
      fi

    # Run ChromeDriver
    - $MINK_DEBUG_CACHE_DIR/chromedriver > $MINK_DEBUG_CACHE_DIR/chromedriver.log 2>&1 &
    - echo -e "Chromedriver was started in the background!\n"

    # Download and configure Selenium
    - |
      if [ ! -f "$MINK_DEBUG_CACHE_DIR"/selenium.jar ] || [ "$(java -jar $MINK_DEBUG_CACHE_DIR/selenium.jar --version | grep -c 3.141.59)" = "0" ]; then
          curl http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar > selenium.jar
          mv selenium.jar "$MINK_DEBUG_CACHE_DIR"
      fi

    # Run Selenium
    - java -Dwebdriver.chrome.driver=$MINK_DEBUG_CACHE_DIR/chromedriver -jar $MINK_DEBUG_CACHE_DIR/selenium.jar > /dev/null 2>&1 &
    - echo -e "Selenium was started in the background!\n"
    - ./travis/tools/wait-for-port 4444

script:
    - composer validate --strict
    - vendor/bin/phpspec run
    - vendor/bin/behat --strict || vendor/bin/behat --strict --rerun

after_failure:
    - cat $MINK_DEBUG_CACHE_DIR/chromedriver.log
    - cat $MINK_DEBUG_CACHE_DIR/selenium.log
