os: linux
dist: bionic
sudo: false
language: php

php:
    - 7.4
    - 7.3
    - 7.2

env:
    global:
        - MINK_DEBUG_CACHE_DIR=$HOME/.mink-debug-cache
        - COMPOSER_OPTIONS=""

jobs:
    include:
        - name: Latest dependencies
        - name: Oldest dependencies
          env: COMPOSER_OPTIONS="--prefer-lowest"

cache:
    directories:
        - ~/composer/.cache
        - $MINK_DEBUG_CACHE_DIR

before_install:
    - phpenv config-rm xdebug.ini || true
    - mkdir -p $MINK_DEBUG_CACHE_DIR
    - composer self-update

install:
    - composer update --prefer-dist $COMPOSER_OPTIONS
    - travis/run-selenium

before_script:
    - travis/tools/wait-for-port 4444

script:
    - composer validate --strict
    - vendor/bin/phpspec run
    - vendor/bin/behat --strict || vendor/bin/behat --strict --rerun
