language: php

sudo: false

php:
    - 7.0
    - 5.6
    - 5.5
    - hhvm

env:
    global:
        - MINK_DEBUG_CACHE_DIR=$HOME/.mink-debug-cache
        - COMPOSER_OPTIONS=""

matrix:
    include:
        - php: 5.5
          env: COMPOSER_OPTIONS="--prefer-lowest"

cache:
    directories:
        - vendor
        - $MINK_DEBUG_CACHE_DIR

before_install:
    - phpenv config-rm xdebug.ini || true

    - mkdir -p $MINK_DEBUG_CACHE_DIR

    - composer self-update

install:
    - composer update --prefer-dist $COMPOSER_OPTIONS

    - travis/run-selenium

before_script:
    - travis/tools/wait-for-port 4444

script:
    - composer validate --strict
    - vendor/bin/phpspec run
    - vendor/bin/behat --strict -vv || vendor/bin/behat --strict --rerun
    - ls -lah test-application/logs
