os: linux
dist: bionic
language: php

env:
    global:
        - MINK_DEBUG_CACHE_DIR=$HOME/.mink-debug-cache
        - COMPOSER_OPTIONS=""

jobs:
    include:
        - name: PHP 7.4 Latest dependencies
          php: 7.4
        - name: PHP 7.4 Oldest dependencies
          php: 7.4
          env: COMPOSER_OPTIONS="--prefer-lowest"
        - name: PHP 7.3 Latest dependencies
          php: 7.3
        - name: PHP 7.3 Oldest dependencies
          php: 7.3
          env: COMPOSER_OPTIONS="--prefer-lowest"
        - name: PHP 7.2 Latest dependencies
          php: 7.2
        - name: PHP 7.2 Oldest dependencies
          php: 7.2
          env: COMPOSER_OPTIONS="--prefer-lowest"

cache:
    directories:
        - ~/composer/.cache
        - $MINK_DEBUG_CACHE_DIR

before_install:
    - phpenv config-rm xdebug.ini || true
    - mkdir -p $MINK_DEBUG_CACHE_DIR
    - composer self-update

install:
    - composer update --prefer-dist $COMPOSER_OPTIONS
    - travis/run-selenium

before_script:
    - travis/tools/wait-for-port 4444

script:
    - composer validate --strict
    - vendor/bin/phpspec run
    - vendor/bin/behat --strict || vendor/bin/behat --strict --rerun

after_failure:
    - cat "$MINK_DEBUG_CACHE_DIR/chromedriver.log"
    - cat "$MINK_DEBUG_CACHE_DIR/selenium.log"
