#!/bin/bash

COUNTER=15
while [ $COUNTER -gt 0 ]
do
    if [ `echo | telnet localhost $1 2>&1 | grep 'Connection refused' | wc -l` == 0 ]
    then
        break
    fi

    echo "$COUNTER - Connection refused on port $1. Waiting a second..."
    sleep 1

    let COUNTER-=1
done